apiVersion: v1
kind: ServiceAccount
metadata:
    name: foldify-service-account
    namespace: <your-name-space> # change this to your namespace
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: job-creator
    namespace: <your-name-space> # change this to your namespace
rules:
    - apiGroups: ["batch"]
      resources: ["jobs"]
      verbs: ["get", "watch", "list", "create", "delete"]
    - apiGroups: [""]
      resources: ["pods", "pods/log"]
      verbs: ["get", "watch", "list"]
    - apiGroups: ["metrics.k8s.io"]
      resources: ["pods"]
      verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: bind-foldify-service-account
    namespace: <your-name-space> # change this to your namespace
subjects:
    - kind: ServiceAccount
      name: foldify-service-account
      namespace: <your-name-space> # change this to your namespace
roleRef:
    kind: Role
    name: job-creator
    apiGroup: rbac.authorization.k8s.io
