apiVersion: v1
kind: Secret
metadata:
  name: foldify-ssmtp-secret
type: Opaque
stringData:
  ssmtp.conf: |
    # Configure based on the manual:https://linux.die.net/man/5/ssmtp.conf
    Root=postmaster
    Mailhub=
    FromLineOverride=
    AuthUser=
    AuthPass=
    AuthMethod=
    UseTLS=
