# Copyright 2021 DeepMind Technologies Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG CUDA=12.9.2
FROM nvidia/cuda:${CUDA}-cudnn-runtime-ubuntu20.04

ARG CUDA

# Use bash to support string substitution.
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update --quiet \
    && apt-get install --no-install-recommends --yes --quiet \
        build-essential \
        cmake \
        cuda-command-line-tools-$(cut -f1,2 -d- <<< ${CUDA//./-}) \
        git \
        hmmer \
        kalign \
        tzdata \
        wget \
        zip ssmtp zlib1g-dev libbz2-dev libopenmpi-dev openmpi-bin \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove --yes \
    && apt-get clean

# Compile HHsuite from source.
RUN git clone --branch v3.3.0 --single-branch https://github.com/soedinglab/hh-suite.git /tmp/hh-suite \
    && mkdir /tmp/hh-suite/build \
    && pushd /tmp/hh-suite/build \
    && cmake -DCMAKE_INSTALL_PREFIX=/opt/hhsuite .. \
    && make -j && make install \
    && ln -s /opt/hhsuite/bin/* /usr/bin \
    && popd \
    && rm -rf /tmp/hh-suite

# Install Miniconda package manager.
RUN wget -q -P /tmp \
  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda \
    && rm /tmp/Miniconda3-latest-Linux-x86_64.sh

# Install Conda packages.
ENV PATH="/opt/conda/bin:$PATH"
ENV HOME="/home/jovyan"
ENV CONDA_PLUGINS_AUTO_ACCEPT_TOS="yes"

RUN conda install --quiet --yes conda==24.11.1 pip python=3.11 \
    && conda install --quiet --yes --channel nvidia cuda=${CUDA_VERSION} \
    && conda clean --all --force-pkgs-dirs --yes

WORKDIR /app/alphafold

# Install pip packages.
RUN pip3 install --upgrade pip --no-cache-dir \
    && pip3 install -q --no-warn-conflicts --no-cache-dir "colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold@v1.6.1" \
    "jax[cuda12_local]==0.5.2"

RUN useradd -l -m -s /bin/bash -N -u 1000 jovyan \
    && mkdir -p /home/jovyan/.cache \
    && chown -R jovyan /home/jovyan/.cache \
    && chmod -R a+rwx /home/jovyan \
    && chmod -R a+rx /app/alphafold
